#!/bin/sh

# wrap-for-bin.sh: Template for git executable wrapper scripts
# to run test suite against sandbox, but with only bindir-installed
# executables in PATH.  The Makefile copies this into various
# files in bin-wrappers, substituting
# /root/TPshop/git-2.3.0 and git.

GIT_EXEC_PATH='/root/TPshop/git-2.3.0'
if test -n "$NO_SET_GIT_TEMPLATE_DIR"
then
	unset GIT_TEMPLATE_DIR
else
	GIT_TEMPLATE_DIR='/root/TPshop/git-2.3.0/templates/blt'
	export GIT_TEMPLATE_DIR
fi
GITPERLLIB='/root/TPshop/git-2.3.0/perl/blib/lib'"${GITPERLLIB:+:$GITPERLLIB}"
GIT_TEXTDOMAINDIR='/root/TPshop/git-2.3.0/po/build/locale'
PATH='/root/TPshop/git-2.3.0/bin-wrappers:'"$PATH"
export GIT_EXEC_PATH GITPERLLIB PATH GIT_TEXTDOMAINDIR

exec "${GIT_EXEC_PATH}/git" "$@"
