<?php

namespace app\home\controller;

use think\Controller;
use think\Request;

class Base extends Controller
{
    // public function __construct(Request $request)
    // {
    //     parent::__construct($request);
    //     //查询所有的分类
    //     $this->getCategory();
    // }

    // //查询所有的分类 父子树状结构
    // public function getCategory()
    // {
    //     //先尝试取缓存
    //     $category = cache('category');
    //     if(empty($category)){
    //         //查询所有的分类
    //         $category = \app\common\model\Category::select();
    //         //转化为标准的二维数组
    //         $category = (new \think\Collection($category))->toArray();
    //         //转化为父子树状结构
    //         $category = get_tree_list($category);
    //         //存储到缓存
    //         cache('category',$category,86400);
    //     }
    //     //变量赋值
    //     $this->assign('category',$category);
    // }
    
    //所以界面继承了Base控制器 这个构造函数会自动调用 在所有页面效果展示
    public function __construct(Request $request)
    {
        parent::__construct($request);
       $this->getCategory();
    }

    public function getCategory()
    {
        //查询所有的分类数据
        $category = \app\common\model\Category::select();
        $category = (new \think\Collection($category))->toArray();
        //转化为父子树状结构
        $category = get_tree_list($category);
        $this->assign('category', $category);
    }

    /*public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }*/
}
